ruby_lessons/myblog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources:posts
  resources:letters
  root 'letters#index'
end

ruby_lessons/myblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby_lessons/myblog/app/models/box.rb
class Box < ApplicationRecord
end

ruby_lessons/myblog/app/models/letter.rb
class Letter < ApplicationRecord
end

ruby_lessons/myblog/app/models/post.rb
class Post < ApplicationRecord
end

ruby_lessons/myblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ruby_lessons/myblog/app/controllers/letters_controller.rb
class LettersController < ApplicationController
    
    def index
        @letters = Letter.all.order(created_at:'desc')
    end
    
    def show
        # render plain:params[:id].inspect
        @letter = Letter.find(params[:id])
        # render plain:@letter.inspect
    end
end

ruby_lessons/myblog/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_lessons/myblog/app/helpers/letters_helper.rb
module LettersHelper
end

ruby_lessons/myblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ruby_lessons/myblog/app/views/letters/index.html.erb
<h2>My Letters</h2>
<ul>
    <% @letters.each do |letter| %>
    <li>
        <%= link_to letter.title , letter_path(letter) %>
    </li>
    <% end %>
</ul>

ruby_lessons/myblog/app/views/letters/show.html.erb
<%= link_to image_tag('rails_sample.png', class:'logo'), root_path%>
<h2>Letter Detail</h2>
<ul>
    <li>
        <%= @letter.title %>
    </li>
    <p>
        <%= @letter.body %>
    </p>
</ul>